# Generated by Django 5.1.4 on 2025-10-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inheritance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=100, verbose_name='被相続人の氏名')),
                ('estate_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='遺産総額（万円）')),
                ('heirs', models.TextField(verbose_name='相続人情報')),
                ('has_house', models.BooleanField(default=False, verbose_name='不動産（家）の有無')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='不動産住所')),
                ('house_built_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='築年数')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('built_year', models.IntegerField(blank=True, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('transfer_password', models.CharField(max_length=8)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inheritances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
