# Generated by Django 5.1.4 on 2025-09-30 16:50

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inheritance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=100, verbose_name='被相続人の氏名')),
                ('estate_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='遺産総額（万円）')),
                ('heirs', models.TextField(verbose_name='相続人情報')),
                ('has_house', models.BooleanField(default=False, verbose_name='不動産（家）の有無')),
                ('transfer_password', models.CharField(default=project.models.generate_transfer_password, editable=False, max_length=8, unique=True, verbose_name='引継ぎパスワード')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
