# Generated by Django 5.1.4 on 2025-10-28 04:52

import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inheritance',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='inheritance',
            name='built_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='建築年'),
        ),
        migrations.AlterField(
            model_name='inheritance',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='土地/建物の面積(㎡)'),
        ),
        migrations.AlterField(
            model_name='inheritance',
            name='transfer_password',
            field=models.CharField(default=project.models.generate_transfer_password, editable=False, max_length=8, unique=True, verbose_name='引継ぎパスワード'),
        ),
    ]
