# Generated by Django 5.1.4 on 2025-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_inheritance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inheritance',
            name='house_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='不動産住所'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='house_built_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='築年数'),
        ),
    ]
