# Generated by Django 5.1.4 on 2025-10-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_inheritance_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inheritance',
            name='address',
        ),
        migrations.RemoveField(
            model_name='inheritance',
            name='built_year',
        ),
        migrations.AddField(
            model_name='inheritance',
            name='business_assets',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='事業用財産'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='cash_deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='現金・預貯金'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='debt',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='債務'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='foreign_assets',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='外貨（円換算）'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='funeral_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='葬儀費用'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='household_goods',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='家庭用財産'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='life_insurance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='生命保険・死亡退職手当'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='others',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='その他の財産'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='securities',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='有価証券'),
        ),
        migrations.AlterField(
            model_name='inheritance',
            name='estate_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='遺産総額（円）'),
        ),
    ]
