# Generated by Django 5.1.4 on 2025-10-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_inheritance_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inheritance',
            old_name='size',
            new_name='house_size',
        ),
        migrations.AddField(
            model_name='inheritance',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='住所'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='deceased_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='deceased_name_kana',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ふりがな'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='inheritance_settlement_date',
            field=models.DateField(blank=True, null=True, verbose_name='遺産分割完了日'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='職業'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号'),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='tax_office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='申告書提出先'),
        ),
        migrations.AlterField(
            model_name='inheritance',
            name='deceased_name',
            field=models.CharField(max_length=100, verbose_name='氏名'),
        ),
    ]
