# Generated by Django 5.1.4 on 2025-10-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_inheritance_house_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inheritance',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='built_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inheritance',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='inheritance',
            name='transfer_password',
            field=models.CharField(max_length=8),
        ),
    ]
