# Generated by Django 5.1.4 on 2025-10-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_rename_size_inheritance_house_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inheritance',
            name='inheritance_settlement_date',
            field=models.DateField(blank=True, null=True, verbose_name='遺産分割完了日YY-MM-DD'),
        ),
    ]
